# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _kinematicsUtils
else:
    import _kinematicsUtils

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def dcmInr2Ric(arg1, arg2, INPLACE_ARRAY2):
    return _kinematicsUtils.dcmInr2Ric(arg1, arg2, INPLACE_ARRAY2)

def dcmRic2Los(IN_ARRAY1, INPLACE_ARRAY2):
    return _kinematicsUtils.dcmRic2Los(IN_ARRAY1, INPLACE_ARRAY2)

def rv2ric(arg1, arg2, arg3, arg4, arg5, arg6):
    return _kinematicsUtils.rv2ric(arg1, arg2, arg3, arg4, arg5, arg6)

def ric2rv(arg1, arg2, arg3, arg4, arg5, arg6):
    return _kinematicsUtils.ric2rv(arg1, arg2, arg3, arg4, arg5, arg6)

def curvRic2rectRic(arg1, arg2, arg3, arg4, arg5, arg6):
    return _kinematicsUtils.curvRic2rectRic(arg1, arg2, arg3, arg4, arg5, arg6)

def rectRic2curvRic(arg1, arg2, arg3, arg4, arg5, arg6):
    return _kinematicsUtils.rectRic2curvRic(arg1, arg2, arg3, arg4, arg5, arg6)

def clroe2ric(IN_ARRAY1, n, t, arg4, arg5):
    return _kinematicsUtils.clroe2ric(IN_ARRAY1, n, t, arg4, arg5)

def ric2clroe(arg1, arg2, n, t, INPLACE_ARRAY1):
    return _kinematicsUtils.ric2clroe(arg1, arg2, n, t, INPLACE_ARRAY1)

def oe2roe(arg1, arg2, INPLACE_ARRAY1):
    return _kinematicsUtils.oe2roe(arg1, arg2, INPLACE_ARRAY1)

def measParams(arg1, arg2):
    return _kinematicsUtils.measParams(arg1, arg2)

def envAngles(arg1, arg2, arg3, arg4):
    return _kinematicsUtils.envAngles(arg1, arg2, arg3, arg4)

def oe2rv(mu, IN_ARRAY1, arg3, arg4):
    return _kinematicsUtils.oe2rv(mu, IN_ARRAY1, arg3, arg4)

def rv2oe(mu, arg2, arg3, INPLACE_ARRAY1):
    return _kinematicsUtils.rv2oe(mu, arg2, arg3, INPLACE_ARRAY1)

def oe2ee(IN_ARRAY1, INPLACE_ARRAY1):
    return _kinematicsUtils.oe2ee(IN_ARRAY1, INPLACE_ARRAY1)

def ee2rv(mu, IN_ARRAY1, arg3, arg4):
    return _kinematicsUtils.ee2rv(mu, IN_ARRAY1, arg3, arg4)

def rv2ee(mu, arg2, arg3, INPLACE_ARRAY1):
    return _kinematicsUtils.rv2ee(mu, arg2, arg3, INPLACE_ARRAY1)

def E2f(E, e):
    return _kinematicsUtils.E2f(E, e)

def E2M(E, e):
    return _kinematicsUtils.E2M(E, e)

def f2E(f, e):
    return _kinematicsUtils.f2E(f, e)

def M2E(M, e):
    return _kinematicsUtils.M2E(M, e)

